version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: psico
      POSTGRES_USER: postgres
      POSTGRES_DB: db_psico
    network_mode: host

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
